### ISSUE TITLE
Complex objects with arrays

### ISSUE THREAD

**Issue by lelong37** [wattsm/odata-graph-delta#1]
Seems to be failing when a complex object is an array e.g. Customer -> Orders []

**Comment by wattsm** [comment]
Hi @lelong37 - it's very hard to write a generic solution for updating collections (particularly of complex types) - e.g. if you have a Customer with 3 Orders and a PATCH is made with just a single Order what do you do? Update that single order (if so how do you identify which Order is to be updated?) or replace the entire collection? 

This implementation is purposefully minimal. How items are matched in a collection will be specific to your model - e.g. we update items contained in collections (rather than changing the collections themselves), using value annotations on the metadata to mark properties of complex types as keys.

**Comment by lelong37** [comment]
Thanks for the response, I'm on the URF team (coordinator), was wondering if there is anyway to get your implementation working with ours (https://genericunitofworkandrepositories.codeplex.com/SourceControl/latest#main/Source/Repository.Pattern.Ef6/Repository.cs - see method SyncObjectGraph)... Our entities inherit Entity.cs (https://genericunitofworkandrepositories.codeplex.com/SourceControl/latest#main/Source/Repository.Pattern.Ef6/Entity.cs) which we use to keep track of ObjectState (https://genericunitofworkandrepositories.codeplex.com/SourceControl/latest#main/Source/Repository.Pattern/Infrastructure/ObjectState.cs), assuming that this is passed into your Delta<>, could we make this work? Meaning each element in a collection would be marked (ObjectState.Add, Modified, Deleted, etc..).

**Comment by wattsm** [comment]
It is possible so long as you have a way of matching records between the delta and the model - e.g. using your Customer and Order example if you have an OrderNo property that could be marked in some way (e.g. attribute) as being used for record matching. 

Our internal version of this has a method `ReadCollections` similar to `ReadRoot` and `ReadChildren` that looks for properties which implement `ICollection<T>` and do not contain value types or strings. This creates an `IDictionary<String, IEnumerable<TypedGraphDelta>>` of deltas for the collection items.

When applying a collection from a delta to a model we iterate over the items contained in the delta's collection and lookup the corresponding item in the model's collection. We do not support add/delete this way - but it can be done easily enough. If an item exists in the delta's collection but not the model then it's an add, and items which exist in the model's collection but not the delta then it's a delete.

Pseudo-code:

```
foreach(var deltaCollection in _collections) {
  
  var modelCollection = this.GetModelCollection(deltaCollection, model);

  //Mark everything as deleted and then change to added/edited as we iterate through.
  //This seems easier than recording what we have added/edited and then applying
  //the delete flag later.
  foreach(var modelCollectionItem in modelCollection) {
    modelCollectionItem.State = ObjectState.Deleted;
  }

  //Iterate over delta collection items adding and updating as appropriate
  foreach(var deltaCollectionItem in deltaCollection) {
  
    var modelCollectionItem = this.LookupCollectionItem(deltaCollectionItem, modelCollection);

    if(modelCollectionItem != null) {
 
      //Update the state to updated
      modelCollectionItem.State = ObjectState.Updated;

    } else {
  
      //Create a blank item, set its state to added and add it to the collection
      modelCollectionItem = new ModelCollectionItem(); 
      modelCollectionItem.State = ObjectState.Added;

      modelCollection.Add(modelCollectionItem);
    }

     //Apply the patch
     deltaCollectionItem.Patch(modelCollectionItem);
  }
}
```

For a generic solution all of those helper methods are likely going to contain a lot of reflection.

**Comment by lelong37** [comment]
Thanks @wattsm, team is reviewing this, obviously if we implement this in anyway, we will reference this in our release notes.

**Comment by wattsm** [comment]
No problem :-) Any other queries just re-open the issue.
